# -*- coding: utf-8 -*-
"""Vaccination_Data_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DiImfflNIiSdvPZvIVFHgxhJIUvYkhUv
"""



from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_excel("cleaned_coverage-data.xlsx")

print("Dataset loaded successfully!")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print(df.columns.tolist())

print("Missing Values in Each Column:")
print(df.isnull().sum())

df["NAME"] = df["NAME"].fillna("Unknown")

print("Missing NAME values:", df["NAME"].isnull().sum())

print("TARGET_NUMBER missing values:", df["TARGET_NUMBER"].isnull().sum())

print("TARGET_NUMBER available values:", df["TARGET_NUMBER"].notnull().sum())

print("DOSES missing values:", df["DOSES"].isnull().sum())

print("DOSES available values:", df["DOSES"].notnull().sum())

print("COVERAGE missing values:", df["COVERAGE"].isnull().sum())

print("COVERAGE available values:", df["COVERAGE"].notnull().sum())

print(df["COVERAGE"].describe())

print("Coverage values greater than 100:", (df["COVERAGE"] > 100).sum())

print("Coverage values greater than 1000:", (df["COVERAGE"] > 1000).sum())

# ==========================================
# COVERAGE DATA - COMPLETE DATA QUALITY CHECK
# ==========================================

print("===== COVERAGE DATA QUALITY REPORT =====")

# 1. Missing values
print("\n1. Missing Values:")
print(df.isnull().sum())

# 2. Duplicate rows
print("\n2. Duplicate Rows:")
print(df.duplicated().sum())

# 3. Coverage statistics
print("\n3. Coverage Statistics:")
print(df["COVERAGE"].describe())

# 4. Coverage greater than 100
print("\n4. Coverage > 100:")
print((df["COVERAGE"] > 100).sum())

# 5. Coverage greater than 1000
print("\n5. Coverage > 1000:")
print((df["COVERAGE"] > 1000).sum())

# 6. Coverage between 0 and 100
print("\n6. Coverage between 0 and 100:")
print(((df["COVERAGE"] >= 0) & (df["COVERAGE"] <= 100)).sum())

# 7. Data types
print("\n7. Data Types:")
print(df.dtypes)

# 8. Dataset shape
print("\n8. Dataset Shape:")
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\n===== CHECK COMPLETED =====")

# Basic Coverage Analysis

print("Coverage by Year:")
print(df.groupby("YEAR")["COVERAGE"].mean().tail(10))

# Year-wise Vaccination Coverage Trend

yearly_coverage = (
    df.groupby("YEAR")["COVERAGE"]
      .mean()
      .reset_index()
)

print(yearly_coverage)

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))
plt.plot(
    yearly_coverage["YEAR"],
    yearly_coverage["COVERAGE"],
    marker="o"
)

plt.title("Year-wise Average Vaccination Coverage")
plt.xlabel("Year")
plt.ylabel("Average Coverage (%)")
plt.grid(True)
plt.show()

print("Highest Average Coverage:")
print(yearly_coverage.loc[yearly_coverage["COVERAGE"].idxmax()])

print("\nLowest Average Coverage:")
print(yearly_coverage.loc[yearly_coverage["COVERAGE"].idxmin()])

# ==========================================
# COVERAGE DATA - EDA SUMMARY
# ==========================================

print("========== COVERAGE EDA SUMMARY ==========")

# 1. Total records
print("\n1. Total Records:")
print(len(df))

# 2. Number of countries/regions
print("\n2. Unique Countries/Regions:")
print(df["NAME"].nunique())

# 3. Year range
print("\n3. Year Range:")
print("From:", df["YEAR"].min())
print("To:", df["YEAR"].max())

# 4. Unique antigens
print("\n4. Unique Antigens:")
print(df["ANTIGEN"].nunique())

# 5. Average coverage
print("\n5. Overall Average Coverage:")
print(round(df["COVERAGE"].mean(), 2), "%")

# 6. Highest average coverage year
highest = yearly_coverage.loc[yearly_coverage["COVERAGE"].idxmax()]
print("\n6. Highest Average Coverage:")
print("Year:", int(highest["YEAR"]))
print("Coverage:", round(highest["COVERAGE"], 2), "%")

# 7. Lowest average coverage year
lowest = yearly_coverage.loc[yearly_coverage["COVERAGE"].idxmin()]
print("\n7. Lowest Average Coverage:")
print("Year:", int(lowest["YEAR"]))
print("Coverage:", round(lowest["COVERAGE"], 2), "%")

# 8. Coverage between 0 and 100
valid_coverage = df[
    (df["COVERAGE"] >= 0) &
    (df["COVERAGE"] <= 100)
]

print("\n8. Valid Coverage Records (0-100):")
print(len(valid_coverage))

# 9. Coverage greater than 100
print("\n9. Coverage > 100:")
print((df["COVERAGE"] > 100).sum())

# 10. Duplicate records
print("\n10. Duplicate Records:")
print(df.duplicated().sum())

print("\n========== EDA COMPLETED ==========")

# Load Incidence Rate Dataset

incidence_df = pd.read_excel("cleaned_incidence-rate-data.xlsx")

print("Incidence Rate Dataset loaded successfully!")
print("Rows:", incidence_df.shape[0])
print("Columns:", incidence_df.shape[1])

# ==========================================
# INCIDENCE RATE - DATA QUALITY CHECK
# ==========================================

print("===== INCIDENCE RATE DATA QUALITY REPORT =====")

print("\n1. Columns:")
print(incidence_df.columns.tolist())

print("\n2. Missing Values:")
print(incidence_df.isnull().sum())

print("\n3. Duplicate Rows:")
print(incidence_df.duplicated().sum())

print("\n4. Dataset Shape:")
print("Rows:", incidence_df.shape[0])
print("Columns:", incidence_df.shape[1])

print("\n===== CHECK COMPLETED =====")

print("===== INCIDENCE RATE STATISTICS =====")

print("\nBasic Statistics:")
print(incidence_df["INCIDENCE_RATE"].describe())

print("\nData Types:")
print(incidence_df.dtypes)

print("\nYear Range:")
print("From:", incidence_df["YEAR"].min())
print("To:", incidence_df["YEAR"].max())

print("\nUnique Diseases:")
print(incidence_df["DISEASE"].nunique())

print("\nUnique Countries/Regions:")
print(incidence_df["NAME"].nunique())

print("\n===== STATISTICS COMPLETED =====")

print("===== INCIDENCE RATE DISTRIBUTION CHECK =====")

print("Missing values:",
      incidence_df["INCIDENCE_RATE"].isnull().sum())

print("Zero values:",
      (incidence_df["INCIDENCE_RATE"] == 0).sum())

print("Values greater than 0:",
      (incidence_df["INCIDENCE_RATE"] > 0).sum())

print("Values greater than 100:",
      (incidence_df["INCIDENCE_RATE"] > 100).sum())

print("Values greater than 1000:",
      (incidence_df["INCIDENCE_RATE"] > 1000).sum())

print("Maximum incidence rate:",
      incidence_df["INCIDENCE_RATE"].max())

print("===== INCIDENCE RATE EXTREME VALUES ANALYSIS =====")

# 1. Highest incidence rate records
print("\n--- Top 20 Highest Incidence Rates ---")

top_incidence = incidence_df[
    ["GROUP", "CODE", "NAME", "YEAR", "DISEASE", "INCIDENCE_RATE"]
].sort_values(
    by="INCIDENCE_RATE",
    ascending=False
).head(20)

display(top_incidence)


# 2. Incidence rate greater than 1000
print("\n--- Records with Incidence Rate > 1000 ---")

high_incidence = incidence_df[
    incidence_df["INCIDENCE_RATE"] > 1000
][
    ["GROUP", "CODE", "NAME", "YEAR", "DISEASE", "INCIDENCE_RATE"]
].sort_values(
    by="INCIDENCE_RATE",
    ascending=False
)

display(high_incidence.head(20))


# 3. Disease-wise average incidence rate
print("\n--- Disease-wise Average Incidence Rate ---")

disease_incidence = (
    incidence_df
    .groupby("DISEASE")["INCIDENCE_RATE"]
    .mean()
    .sort_values(ascending=False)
)

display(disease_incidence)


# 4. Year-wise average incidence rate
print("\n--- Year-wise Average Incidence Rate ---")

year_incidence = (
    incidence_df
    .groupby("YEAR")["INCIDENCE_RATE"]
    .mean()
    .reset_index()
)

display(year_incidence)


# 5. Basic summary
print("\n===== SUMMARY =====")

print("Highest incidence rate:",
      incidence_df["INCIDENCE_RATE"].max())

print("Lowest incidence rate:",
      incidence_df["INCIDENCE_RATE"].min())

print("Average incidence rate:",
      incidence_df["INCIDENCE_RATE"].mean())

print("Median incidence rate:",
      incidence_df["INCIDENCE_RATE"].median())

print("Number of diseases:",
      incidence_df["DISEASE"].nunique())

print("Number of countries/regions:",
      incidence_df["NAME"].nunique())

print("Year range:",
      incidence_df["YEAR"].min(),
      "to",
      incidence_df["YEAR"].max())

# ==========================================
# INCIDENCE RATE - MISSING & EXTREME ANALYSIS
# ==========================================

print("===== MISSING VALUE ANALYSIS =====")

# Disease-wise missing values
missing_by_disease = (
    incidence_df[incidence_df["INCIDENCE_RATE"].isnull()]
    .groupby("DISEASE")
    .size()
    .sort_values(ascending=False)
)

print("\nMissing INCIDENCE_RATE by Disease:")
display(missing_by_disease)


# Year-wise missing values
missing_by_year = (
    incidence_df[incidence_df["INCIDENCE_RATE"].isnull()]
    .groupby("YEAR")
    .size()
    .reset_index(name="Missing_Count")
)

print("\nMissing INCIDENCE_RATE by Year:")
display(missing_by_year.head(20))


# ==========================================
# EXTREME VALUE ANALYSIS
# ==========================================

print("\n===== EXTREME VALUE ANALYSIS =====")

# Count by disease for values > 100
greater_100 = (
    incidence_df[incidence_df["INCIDENCE_RATE"] > 100]
    .groupby("DISEASE")
    .size()
    .sort_values(ascending=False)
)

print("\nValues > 100 by Disease:")
display(greater_100)


# Count by disease for values > 1000
greater_1000 = (
    incidence_df[incidence_df["INCIDENCE_RATE"] > 1000]
    .groupby("DISEASE")
    .size()
    .sort_values(ascending=False)
)

print("\nValues > 1000 by Disease:")
display(greater_1000)


# ==========================================
# ZERO VALUE ANALYSIS
# ==========================================

print("\n===== ZERO VALUE ANALYSIS =====")

zero_by_disease = (
    incidence_df[incidence_df["INCIDENCE_RATE"] == 0]
    .groupby("DISEASE")
    .size()
    .sort_values(ascending=False)
)

print("\nZero Incidence Rate by Disease:")
display(zero_by_disease)


# ==========================================
# VALID DATA RANGE
# ==========================================

print("\n===== FINAL INCIDENCE DATA SUMMARY =====")

print("Total records:", len(incidence_df))

print("Missing incidence:",
      incidence_df["INCIDENCE_RATE"].isnull().sum())

print("Zero incidence:",
      (incidence_df["INCIDENCE_RATE"] == 0).sum())

print("Positive incidence:",
      (incidence_df["INCIDENCE_RATE"] > 0).sum())

print("Above 100:",
      (incidence_df["INCIDENCE_RATE"] > 100).sum())

print("Above 1000:",
      (incidence_df["INCIDENCE_RATE"] > 1000).sum())

print("Maximum incidence:",
      incidence_df["INCIDENCE_RATE"].max())

print("Minimum incidence:",
      incidence_df["INCIDENCE_RATE"].min())

print("Mean incidence:",
      incidence_df["INCIDENCE_RATE"].mean())

print("Median incidence:",
      incidence_df["INCIDENCE_RATE"].median())

# ==========================================
# INCIDENCE RATE - MISSING VALUE HANDLING
# ==========================================

print("===== BEFORE CLEANING =====")

print("Total records:",
      len(incidence_df))

print("Missing INCIDENCE_RATE:",
      incidence_df["INCIDENCE_RATE"].isnull().sum())

print("Zero INCIDENCE_RATE:",
      (incidence_df["INCIDENCE_RATE"] == 0).sum())


# ------------------------------------------
# Create a separate dataframe for analysis
# ------------------------------------------

incidence_clean = incidence_df.dropna(
    subset=["INCIDENCE_RATE"]
).copy()


# ------------------------------------------
# Check after removing missing values
# ------------------------------------------

print("\n===== AFTER REMOVING MISSING VALUES =====")

print("Total records:",
      len(incidence_clean))

print("Missing INCIDENCE_RATE:",
      incidence_clean["INCIDENCE_RATE"].isnull().sum())

print("Zero INCIDENCE_RATE:",
      (incidence_clean["INCIDENCE_RATE"] == 0).sum())

print("Positive INCIDENCE_RATE:",
      (incidence_clean["INCIDENCE_RATE"] > 0).sum())


# ------------------------------------------
# Check duplicates
# ------------------------------------------

print("\n===== DUPLICATE CHECK =====")

print("Duplicate rows:",
      incidence_clean.duplicated().sum())


# ------------------------------------------
# Final statistics
# ------------------------------------------

print("\n===== CLEAN INCIDENCE SUMMARY =====")

print("Minimum:",
      incidence_clean["INCIDENCE_RATE"].min())

print("Maximum:",
      incidence_clean["INCIDENCE_RATE"].max())

print("Mean:",
      incidence_clean["INCIDENCE_RATE"].mean())

print("Median:",
      incidence_clean["INCIDENCE_RATE"].median())

print("Number of diseases:",
      incidence_clean["DISEASE"].nunique())

print("Number of countries/regions:",
      incidence_clean["NAME"].nunique())

print("Year range:",
      incidence_clean["YEAR"].min(),
      "to",
      incidence_clean["YEAR"].max())

# ==========================================
# YEAR-WISE INCIDENCE RATE TREND
# ==========================================

year_incidence_clean = (
    incidence_clean
    .groupby("YEAR")["INCIDENCE_RATE"]
    .mean()
    .reset_index()
)

print("===== YEAR-WISE INCIDENCE RATE =====")

display(year_incidence_clean)


# Find highest and lowest average year
highest_year = year_incidence_clean.loc[
    year_incidence_clean["INCIDENCE_RATE"].idxmax()
]

lowest_year = year_incidence_clean.loc[
    year_incidence_clean["INCIDENCE_RATE"].idxmin()
]

print("\n===== TREND SUMMARY =====")

print(
    "Highest average incidence year:",
    int(highest_year["YEAR"]),
    "Rate:",
    round(highest_year["INCIDENCE_RATE"], 2)
)

print(
    "Lowest average incidence year:",
    int(lowest_year["YEAR"]),
    "Rate:",
    round(lowest_year["INCIDENCE_RATE"], 2)
)

# ==========================================
# YEAR-WISE INCIDENCE RATE TREND
# ==========================================

year_incidence_clean = (
    incidence_clean
    .groupby("YEAR")["INCIDENCE_RATE"]
    .mean()
    .reset_index()
)

print("===== YEAR-WISE INCIDENCE RATE =====")

display(year_incidence_clean)


# Find highest and lowest average year
highest_year = year_incidence_clean.loc[
    year_incidence_clean["INCIDENCE_RATE"].idxmax()
]

lowest_year = year_incidence_clean.loc[
    year_incidence_clean["INCIDENCE_RATE"].idxmin()
]

print("\n===== TREND SUMMARY =====")

print(
    "Highest average incidence year:",
    int(highest_year["YEAR"]),
    "Rate:",
    round(highest_year["INCIDENCE_RATE"], 2)
)

print(
    "Lowest average incidence year:",
    int(lowest_year["YEAR"]),
    "Rate:",
    round(lowest_year["INCIDENCE_RATE"], 2)
)

# ==========================================
# DISEASE-WISE INCIDENCE RATE ANALYSIS
# ==========================================

disease_incidence_clean = (
    incidence_clean
    .groupby("DISEASE")["INCIDENCE_RATE"]
    .agg(
        Average_Incidence="mean",
        Median_Incidence="median",
        Minimum_Incidence="min",
        Maximum_Incidence="max",
        Record_Count="count"
    )
    .reset_index()
    .sort_values(
        by="Average_Incidence",
        ascending=False
    )
)

print("===== DISEASE-WISE INCIDENCE ANALYSIS =====")

display(disease_incidence_clean)


# ------------------------------------------
# Highest and Lowest Average Incidence
# ------------------------------------------

highest_disease = disease_incidence_clean.iloc[0]

lowest_disease = disease_incidence_clean.iloc[-1]

print("\n===== DISEASE SUMMARY =====")

print(
    "Highest average incidence disease:",
    highest_disease["DISEASE"],
    "| Average:",
    round(highest_disease["Average_Incidence"], 2)
)

print(
    "Lowest average incidence disease:",
    lowest_disease["DISEASE"],
    "| Average:",
    round(lowest_disease["Average_Incidence"], 2)
)

# ==========================================
# DISEASE-WISE AVERAGE INCIDENCE RATE CHART
# ==========================================

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))

plt.bar(
    disease_incidence_clean["DISEASE"],
    disease_incidence_clean["Average_Incidence"]
)

plt.title("Disease-wise Average Incidence Rate")
plt.xlabel("Disease")
plt.ylabel("Average Incidence Rate")

plt.xticks(rotation=45)
plt.tight_layout()

plt.show()

# ==========================================
# COVERAGE DATA - ANTIGEN CHECK
# ==========================================

print("===== COVERAGE ANTIGEN LIST =====")

coverage_antigens = (
    df["ANTIGEN"]
    .dropna()
    .unique()
)

print("Total unique antigens:", len(coverage_antigens))

for antigen in sorted(coverage_antigens):
    print(antigen)

# ==========================================
# DISEASE - VACCINATION ANTIGEN MAPPING
# ==========================================

disease_antigen_mapping = {
    "MEASLES": [
        "MCV1",
        "MCV2",
        "MCV2X2"
    ],

    "RUBELLA": [
        "RCV1"
    ],

    "POLIO": [
        "POL3",
        "IPV1",
        "IPV2",
        "IPV1_FRAC",
        "IPV2_FRAC"
    ],

    "JAPENC": [
        "JAPENC",
        "JAPENC_1",
        "JAPENC_C"
    ],

    "TYPHOID": [
        "TYPHOID",
        "TYPHOID_CONJ"
    ],

    "YFEVER": [
        "YFV"
    ],

    "DIPHTHERIA": [
        "DIPHCV4",
        "DIPHCV5",
        "DIPHCV6",
        "DTPCV1",
        "DTPCV3"
    ],

    "PERTUSSIS": [
        "DTPCV1",
        "DTPCV3",
        "DIPHCV4",
        "DIPHCV5",
        "DIPHCV6"
    ],

    "TTETANUS": [
        "TT2PLUS",
        "TTCV4",
        "TTCV5",
        "TTCV6"
    ],

    "NTETANUS": [
        "TT2PLUS",
        "TTCV4",
        "TTCV5",
        "TTCV6"
    ],

    "INVASIVE_MENING": [
        "MENACYW_C",
        "MENA_C",
        "MENB_C",
        "MEN_ACYW_CONJ",
        "MEN_A_CONJ",
        "MEN_B"
    ]
}


print("===== DISEASE - ANTIGEN MAPPING =====")

for disease, antigens in disease_antigen_mapping.items():
    print("\n", disease)
    print("Antigens:", ", ".join(antigens))

print("\nTotal diseases mapped:",
      len(disease_antigen_mapping))

# ==========================================
# CHECK MAPPED ANTIGENS IN COVERAGE DATA
# ==========================================

# All antigens from our mapping
mapped_antigens = []

for disease, antigens in disease_antigen_mapping.items():
    mapped_antigens.extend(antigens)

# Remove duplicates
mapped_antigens = sorted(set(mapped_antigens))

print("===== MAPPED ANTIGENS CHECK =====")

print("Total mapped unique antigens:",
      len(mapped_antigens))

print("\nMapped antigens:")
print(mapped_antigens)


# ------------------------------------------
# Coverage records for mapped antigens
# ------------------------------------------

mapped_coverage = df[
    df["ANTIGEN"].isin(mapped_antigens)
].copy()

print("\n===== COVERAGE RECORD CHECK =====")

print("Total coverage records for mapped antigens:",
      len(mapped_coverage))

print("Unique countries/regions:",
      mapped_coverage["CODE"].nunique())

print("Year range:",
      mapped_coverage["YEAR"].min(),
      "to",
      mapped_coverage["YEAR"].max())


# ------------------------------------------
# Antigen-wise record count
# ------------------------------------------

antigen_counts = (
    mapped_coverage
    .groupby("ANTIGEN")
    .size()
    .sort_values(ascending=False)
    .reset_index(name="Record_Count")
)

print("\n===== ANTIGEN-WISE RECORD COUNT =====")

display(antigen_counts)


# ------------------------------------------
# Missing coverage by antigen
# ------------------------------------------

missing_coverage = (
    mapped_coverage
    .groupby("ANTIGEN")["COVERAGE"]
    .apply(lambda x: x.isnull().sum())
    .reset_index(name="Missing_Coverage")
)

print("\n===== MISSING COVERAGE BY ANTIGEN =====")

display(missing_coverage)

# ==========================================
# MEASLES COVERAGE vs MEASLES INCIDENCE
# ==========================================

# ------------------------------------------
# 1. Select Measles vaccination coverage
# ------------------------------------------

measles_coverage = df[
    df["ANTIGEN"].isin(["MCV1", "MCV2", "MCV2X2"])
].copy()

measles_coverage = measles_coverage[
    [
        "CODE",
        "NAME",
        "YEAR",
        "ANTIGEN",
        "COVERAGE"
    ]
]


# ------------------------------------------
# 2. Remove missing coverage
# ------------------------------------------

measles_coverage = measles_coverage.dropna(
    subset=["COVERAGE"]
).copy()


# ------------------------------------------
# 3. Keep reasonable coverage values
# ------------------------------------------
# Values above 100 are retained separately in
# original data, but not used in this basic
# percentage comparison.

measles_coverage_valid = measles_coverage[
    (measles_coverage["COVERAGE"] >= 0) &
    (measles_coverage["COVERAGE"] <= 100)
].copy()


# ------------------------------------------
# 4. Prepare Measles incidence
# ------------------------------------------

measles_incidence = incidence_clean[
    incidence_clean["DISEASE"] == "MEASLES"
].copy()

measles_incidence = measles_incidence[
    [
        "CODE",
        "NAME",
        "YEAR",
        "INCIDENCE_RATE"
    ]
]


# ------------------------------------------
# 5. Merge by Country Code + Year
# ------------------------------------------

measles_analysis = pd.merge(
    measles_coverage_valid,
    measles_incidence,
    on=["CODE", "YEAR"],
    how="inner"
)


# ------------------------------------------
# 6. Display result
# ------------------------------------------

print("===== MEASLES COVERAGE VS INCIDENCE =====")

print("Total analysis records:",
      len(measles_analysis))

print("Unique countries/regions:",
      measles_analysis["CODE"].nunique())

print("Year range:",
      measles_analysis["YEAR"].min(),
      "to",
      measles_analysis["YEAR"].max())

print("\nMissing values:")

display(
    measles_analysis[
        ["COVERAGE", "INCIDENCE_RATE"]
    ].isnull().sum()
)


# ------------------------------------------
# 7. First 20 records

# ==========================================
# MEASLES COVERAGE VS INCIDENCE
# CORRELATION ANALYSIS
# ==========================================

print("===== MEASLES COVERAGE VS INCIDENCE =====")

# Correlation
correlation = measles_analysis[
    ["COVERAGE", "INCIDENCE_RATE"]
].corr()

print("\nCorrelation Matrix:")

display(correlation)


# Extract correlation value
correlation_value = correlation.loc[
    "COVERAGE",
    "INCIDENCE_RATE"
]

print("\nCorrelation between vaccination coverage",
      "and measles incidence:",
      round(correlation_value, 4))


# ------------------------------------------
# Basic statistics
# ------------------------------------------

print("\n===== BASIC STATISTICS =====")

print("Average vaccination coverage:",
      round(measles_analysis["COVERAGE"].mean(), 2))

print("Average measles incidence:",
      round(measles_analysis["INCIDENCE_RATE"].mean(), 2))

print("Median vaccination coverage:",
      round(measles_analysis["COVERAGE"].median(), 2))

print("Median measles incidence:",
      round(measles_analysis["INCIDENCE_RATE"].median(), 2))

# ==========================================
# SCATTER PLOT
# VACCINATION COVERAGE VS MEASLES INCIDENCE
# ==========================================

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))

plt.scatter(
    measles_analysis["COVERAGE"],
    measles_analysis["INCIDENCE_RATE"],
    alpha=0.4
)

plt.title("Measles Vaccination Coverage vs Incidence Rate")
plt.xlabel("Vaccination Coverage (%)")
plt.ylabel("Measles Incidence Rate")

plt.tight_layout()
plt.show()

# ============================================================
# FINAL MEASLES COVERAGE VS INCIDENCE ANALYSIS
# COUNTRY-YEAR LEVEL
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

print("===== FINAL MEASLES ANALYSIS =====")

# ------------------------------------------------------------
# 1. Select Measles vaccination coverage
# ------------------------------------------------------------

measles_coverage = df[
    df["ANTIGEN"].isin(["MCV1", "MCV2", "MCV2X2"])
].copy()

# Keep required columns
measles_coverage = measles_coverage[
    ["CODE", "NAME", "YEAR", "ANTIGEN", "COVERAGE"]
].copy()

# Remove missing coverage
measles_coverage = measles_coverage.dropna(
    subset=["COVERAGE"]
).copy()

# Keep only valid coverage values 0–100
measles_coverage_valid = measles_coverage[
    (measles_coverage["COVERAGE"] >= 0) &
    (measles_coverage["COVERAGE"] <= 100)
].copy()

print("\nMeasles vaccination records:", len(measles_coverage_valid))


# ------------------------------------------------------------
# 2. Aggregate vaccination coverage
#    One country + one year = one observation
# ------------------------------------------------------------

measles_coverage_country_year = (
    measles_coverage_valid
    .groupby(["CODE", "NAME", "YEAR"], as_index=False)["COVERAGE"]
    .mean()
)

print(
    "Country-year vaccination records:",
    len(measles_coverage_country_year)
)


# ------------------------------------------------------------
# 3. Select Measles incidence
# ------------------------------------------------------------

measles_incidence = incidence_clean[
    incidence_clean["DISEASE"] == "MEASLES"
].copy()

measles_incidence = measles_incidence[
    ["CODE", "NAME", "YEAR", "INCIDENCE_RATE"]
].copy()

print(
    "Measles incidence records:",
    len(measles_incidence)
)


# ------------------------------------------------------------
# 4. Merge vaccination coverage and incidence
# ------------------------------------------------------------

measles_final = pd.merge(
    measles_coverage_country_year,
    measles_incidence,
    on=["CODE", "NAME", "YEAR"],
    how="inner"
)

print(
    "\nFinal country-year analysis records:",
    len(measles_final)
)

print(
    "Unique countries/regions:",
    measles_final["CODE"].nunique()
)

print(
    "Year range:",
    measles_final["YEAR"].min(),
    "to",
    measles_final["YEAR"].max()
)


# ------------------------------------------------------------
# 5. Pearson Correlation
# ------------------------------------------------------------

pearson_corr = measles_final[
    ["COVERAGE", "INCIDENCE_RATE"]
].corr().loc[
    "COVERAGE",
    "INCIDENCE_RATE"
]

print("\n===== PEARSON CORRELATION =====")

print(
    "Correlation between vaccination coverage",
    "and measles incidence:",
    round(pearson_corr, 4)
)


# ------------------------------------------------------------
# 6. Spearman Correlation
# ------------------------------------------------------------

spearman_corr = measles_final[
    ["COVERAGE", "INCIDENCE_RATE"]
].corr(
    method="spearman"
).loc[
    "COVERAGE",
    "INCIDENCE_RATE"
]

print("\n===== SPEARMAN CORRELATION =====")

print(
    "Spearman correlation:",
    round(spearman_corr, 4)
)


# ------------------------------------------------------------
# 7. Basic Statistics
# ------------------------------------------------------------

print("\n===== BASIC STATISTICS =====")

print(
    "Average vaccination coverage:",
    round(measles_final["COVERAGE"].mean(), 2)
)

print(
    "Median vaccination coverage:",
    round(measles_final["COVERAGE"].median(), 2)
)

print(
    "Average measles incidence:",
    round(measles_final["INCIDENCE_RATE"].mean(), 2)
)

print(
    "Median measles incidence:",
    round(measles_final["INCIDENCE_RATE"].median(), 2)
)


# ------------------------------------------------------------
# 8. Scatter Plot
# ------------------------------------------------------------

plt.figure(figsize=(10, 6))

plt.scatter(
    measles_final["COVERAGE"],
    measles_final["INCIDENCE_RATE"],
    alpha=0.4
)

plt.title(
    "Measles Vaccination Coverage vs Incidence Rate"
)

plt.xlabel("Vaccination Coverage (%)")

plt.ylabel("Measles Incidence Rate")

plt.tight_layout()

plt.show()


# ------------------------------------------------------------
# 9. Display first 10 records
# ------------------------------------------------------------

print("\n===== SAMPLE FINAL DATA =====")

display(
    measles_final.head(10)
)

# ============================================================
# VACCINATION COVERAGE VS DISEASE INCIDENCE
# ALL MAPPED DISEASES
# ============================================================

import pandas as pd
import numpy as np

print("====================================================")
print("VACCINATION COVERAGE VS DISEASE INCIDENCE ANALYSIS")
print("====================================================")


# ------------------------------------------------------------
# Disease -> Vaccine Antigen Mapping
# ------------------------------------------------------------

disease_antigen_mapping = {
    "MEASLES": ["MCV1", "MCV2", "MCV2X2"],
    "RUBELLA": ["RCV1"],
    "POLIO": ["POL3", "IPV1", "IPV2", "IPV1_FRAC", "IPV2_FRAC"],
    "JAPENC": ["JAPENC", "JAPENC_1", "JAPENC_C"],
    "TYPHOID": ["TYPHOID", "TYPHOID_CONJ"],
    "YFEVER": ["YFV"],
    "DIPHTHERIA": [
        "DIPHCV4", "DIPHCV5", "DIPHCV6",
        "DTPCV1", "DTPCV3"
    ],
    "PERTUSSIS": [
        "DTPCV1", "DTPCV3",
        "DIPHCV4", "DIPHCV5", "DIPHCV6"
    ],
    "TTETANUS": [
        "TT2PLUS", "TTCV4", "TTCV5", "TTCV6"
    ],
    "NTETANUS": [
        "TT2PLUS", "TTCV4", "TTCV5", "TTCV6"
    ],
    "INVASIVE_MENING": [
        "MENACYW_C", "MENA_C", "MENB_C",
        "MEN_ACYW_CONJ", "MEN_A_CONJ", "MEN_B"
    ]
}


# ------------------------------------------------------------
# Store results
# ------------------------------------------------------------

results = []

disease_analysis_data = {}


# ------------------------------------------------------------
# Analyze each disease
# ------------------------------------------------------------

for disease, antigens in disease_antigen_mapping.items():

    print("\n----------------------------------------------------")
    print("Analyzing:", disease)
    print("Antigens:", ", ".join(antigens))
    print("----------------------------------------------------")

    # -----------------------------
    # Vaccination coverage
    # -----------------------------

    coverage_data = df[
        df["ANTIGEN"].isin(antigens)
    ].copy()

    coverage_data = coverage_data[
        ["CODE", "NAME", "YEAR", "ANTIGEN", "COVERAGE"]
    ].copy()

    coverage_data = coverage_data.dropna(
        subset=["COVERAGE"]
    )

    # Keep valid coverage only
    coverage_data = coverage_data[
        (coverage_data["COVERAGE"] >= 0) &
        (coverage_data["COVERAGE"] <= 100)
    ]

    # One country-year = one coverage value
    coverage_country_year = (
        coverage_data
        .

# ============================================================
# VACCINATION COVERAGE VS DISEASE INCIDENCE
# ALL MAPPED DISEASES
# ============================================================

import pandas as pd
import numpy as np

print("====================================================")
print("VACCINATION COVERAGE VS DISEASE INCIDENCE ANALYSIS")
print("====================================================")

# Disease and vaccine antigen mapping

disease_antigen_mapping = {
    "MEASLES": ["MCV1", "MCV2", "MCV2X2"],
    "RUBELLA": ["RCV1"],
    "POLIO": ["POL3", "IPV1", "IPV2", "IPV1_FRAC", "IPV2_FRAC"],
    "JAPENC": ["JAPENC", "JAPENC_1", "JAPENC_C"],
    "TYPHOID": ["TYPHOID", "TYPHOID_CONJ"],
    "YFEVER": ["YFV"],
    "DIPHTHERIA": [
        "DIPHCV4", "DIPHCV5", "DIPHCV6",
        "DTPCV1", "DTPCV3"
    ],
    "PERTUSSIS": [
        "DTPCV1", "DTPCV3",
        "DIPHCV4", "DIPHCV5", "DIPHCV6"
    ],
    "TTETANUS": [
        "TT2PLUS", "TTCV4", "TTCV5", "TTCV6"
    ],
    "NTETANUS": [
        "TT2PLUS", "TTCV4", "TTCV5", "TTCV6"
    ],
    "INVASIVE_MENING": [
        "MENACYW_C", "MENA_C", "MENB_C",
        "MEN_ACYW_CONJ", "MEN_A_CONJ", "MEN_B"
    ]
}

# Store results
results = []

# Store detailed analysis for each disease
disease_analysis_data = {}

# ------------------------------------------------------------
# Disease-wise analysis
# ------------------------------------------------------------

for disease, antigens in disease_antigen_mapping.items():

    print("\n----------------------------------------------")
    print("Analyzing:", disease)
    print("----------------------------------------------")

    # Vaccination coverage data
    coverage_data = df[
        df["ANTIGEN"].isin(antigens)
    ].copy()

    coverage_data = coverage_data[
        ["CODE", "NAME", "YEAR", "ANTIGEN", "COVERAGE"]
    ]

    # Remove missing coverage
    coverage_data = coverage_data.dropna(
        subset=["COVERAGE"]
    )

    # Keep valid coverage between 0 and 100
    coverage_data = coverage_data[
        (coverage_data["COVERAGE"] >= 0) &
        (coverage_data["COVERAGE"] <= 100)
    ]

    # Average multiple antigens at country-year level
    coverage_country_year = (
        coverage_data
        .groupby(
            ["CODE", "NAME", "YEAR"],
            as_index=False
        )["COVERAGE"]
        .mean()
    )

    # Disease incidence data
    incidence_data = incidence_clean[
        incidence_clean["DISEASE"] == disease
    ].copy()

    incidence_data = incidence_data[
        ["CODE", "NAME", "YEAR", "INCIDENCE_RATE"]
    ]

    # Merge coverage and incidence
    analysis_data = pd.merge(
        coverage_country_year,
        incidence_data,
        on=["CODE", "NAME", "YEAR"],
        how="inner"
    )

    # Save detailed data
    disease_analysis_data[disease] = analysis_data

    # Calculate correlations
    if len(analysis_data) >= 2:

        pearson = analysis_data[
            ["COVERAGE", "INCIDENCE_RATE"]
        ].corr(method="pearson").loc[
            "COVERAGE",
            "INCIDENCE_RATE"
        ]

        spearman = analysis_data[
            ["COVERAGE", "INCIDENCE_RATE"]
        ].corr(method="spearman").loc[
            "COVERAGE",
            "INCIDENCE_RATE"
        ]

    else:
        pearson = np.nan
        spearman = np.nan

    # Store summary
    results.append({
        "Disease": disease,
        "Records": len(analysis_data),
        "Countries": analysis_data["CODE"].nunique(),
        "Year_Start": (
            analysis_data["YEAR"].min()
            if len(analysis_data) > 0 else np.nan
        ),
        "Year_End": (
            analysis_data["YEAR"].max()
            if len(analysis_data) > 0 else np.nan
        ),
        "Avg_Coverage": (
            analysis_data["COVERAGE"].mean()
            if len(analysis

results = []

for disease, antigens in disease_antigen_mapping.items():

    c = df[df["ANTIGEN"].isin(antigens)].copy()
    c = c[["CODE", "NAME", "YEAR", "COVERAGE"]]
    c = c.dropna(subset=["COVERAGE"])
    c = c[(c["COVERAGE"] >= 0) & (c["COVERAGE"] <= 100)]

    c = c.groupby(
        ["CODE", "NAME", "YEAR"],
        as_index=False
    )["COVERAGE"].mean()

    i = incidence_clean[
        incidence_clean["DISEASE"] == disease
    ][["CODE", "NAME", "YEAR", "INCIDENCE_RATE"]]

    a = pd.merge(
        c,
        i,
        on=["CODE", "NAME", "YEAR"],
        how="inner"
    )

    p = a["COVERAGE"].corr(a["INCIDENCE_RATE"])
    s = a["COVERAGE"].corr(
        a["INCIDENCE_RATE"],
        method="spearman"
    )

    results.append([
        disease,
        len(a),
        a["CODE"].nunique(),
        round(a["COVERAGE"].mean(), 2),
        round(a["INCIDENCE_RATE"].mean(), 2),
        round(p, 4),
        round(s, 4)
    ])

summary = pd.DataFrame(
    results,
    columns=[
        "Disease",
        "Records",
        "Countries",
        "Avg_Coverage",
        "Avg_Incidence",
        "Pearson",
        "Spearman"
    ]
)

display(summary)

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))

plt.bar(
    summary["Disease"],
    summary["Pearson"]
)

plt.axhline(0, linewidth=1)

plt.title("Vaccination Coverage vs Disease Incidence - Pearson Correlation")
plt.xlabel("Disease")
plt.ylabel("Pearson Correlation")

plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))

plt.bar(
    summary["Disease"],
    summary["Spearman"]
)

plt.axhline(0, linewidth=1)

plt.title(
    "Vaccination Coverage vs Disease Incidence - Spearman Correlation"
)

plt.xlabel("Disease")
plt.ylabel("Spearman Correlation")

plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

# ============================================================
# FIRST DOSE VS SUBSEQUENT DOSE COVERAGE
# ============================================================

dose_comparison = df[
    df["ANTIGEN"].isin([
        "MCV1",
        "MCV2",
        "DTPCV1",
        "DTPCV3"
    ])
].copy()

dose_comparison = dose_comparison.dropna(
    subset=["COVERAGE"]
)

dose_comparison = dose_comparison[
    (dose_comparison["COVERAGE"] >= 0) &
    (dose_comparison["COVERAGE"] <= 100)
]

dose_summary = (
    dose_comparison
    .groupby("ANTIGEN")["COVERAGE"]
    .agg(["count", "mean", "median"])
    .reset_index()
)

dose_summary["mean"] = dose_summary["mean"].round(2)
dose_summary["median"] = dose_summary["median"].round(2)

print("===== FIRST DOSE VS SUBSEQUENT DOSE =====")

display(dose_summary)

# ============================================================
# ACTUAL DOSE DROP-OFF ANALYSIS
# MCV1 vs MCV2
# DTPCV1 vs DTPCV3
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

# ------------------------------------------------------------
# 1. Select required antigens
# ------------------------------------------------------------

dropoff_df = df[
    df["ANTIGEN"].isin(["MCV1", "MCV2", "DTPCV1", "DTPCV3"])
].copy()

# Keep only valid coverage values
dropoff_df = dropoff_df.dropna(subset=["COVERAGE"])

dropoff_df = dropoff_df[
    (dropoff_df["COVERAGE"] >= 0) &
    (dropoff_df["COVERAGE"] <= 100)
]

# ------------------------------------------------------------
# 2. Average duplicate records for same country-year-antigen
# ------------------------------------------------------------

dropoff_df = (
    dropoff_df
    .groupby(["CODE", "NAME", "YEAR", "ANTIGEN"])["COVERAGE"]
    .mean()
    .reset_index()
)

# ------------------------------------------------------------
# 3. Convert antigens into separate columns
# ------------------------------------------------------------

dropoff_pivot = dropoff_df.pivot_table(
    index=["CODE", "NAME", "YEAR"],
    columns="ANTIGEN",
    values="COVERAGE"
).reset_index()

# Remove column index name
dropoff_pivot.columns.name = None

# ------------------------------------------------------------
# 4. Calculate MCV1 -> MCV2 drop-off
# ------------------------------------------------------------

mcv = dropoff_pivot.dropna(
    subset=["MCV1", "MCV2"]
).copy()

mcv["MCV_Dropoff"] = mcv["MCV1"] - mcv["MCV2"]

mcv["MCV_Dropoff_Percent"] = (
    (mcv["MCV1"] - mcv["MCV2"])
    / mcv["MCV1"]
) * 100

# ------------------------------------------------------------
# 5. Calculate DTPCV1 -> DTPCV3 drop-off
# ------------------------------------------------------------

dtp = dropoff_pivot.dropna(
    subset=["DTPCV1", "DTPCV3"]
).copy()

dtp["DTPCV_Dropoff"] = dtp["DTPCV1"] - dtp["DTPCV3"]

dtp["DTPCV_Dropoff_Percent"] = (
    (dtp["DTPCV1"] - dtp["DTPCV3"])
    / dtp["DTPCV1"]
) * 100

# ------------------------------------------------------------
# 6. Summary
# ------------------------------------------------------------

print("========== DOSE DROP-OFF ANALYSIS ==========")

print("\nMCV1 -> MCV2")
print("Records:", len(mcv))
print("Average MCV1 Coverage:", round(mcv["MCV1"].mean(), 2), "%")
print("Average MCV2 Coverage:", round(mcv["MCV2"].mean(), 2), "%")
print("Average Drop-off:", round(mcv["MCV_Dropoff"].mean(), 2), "percentage points")
print(
    "Average Drop-off %:",
    round(mcv["MCV_Dropoff_Percent"].mean(), 2),
    "%"
)

print("\nDTPCV1 -> DTPCV3")
print("Records:", len(dtp))
print("Average DTPCV1 Coverage:", round(dtp["DTPCV1"].mean(), 2), "%")
print("Average DTPCV3 Coverage:", round(dtp["DTPCV3"].mean(), 2), "%")
print(
    "Average Drop-off:",
    round(dtp["DTPCV_Dropoff"].mean(), 2),
    "percentage points"
)
print(
    "Average Drop-off %:",
    round(dtp["DTPCV_Dropoff_Percent"].mean(), 2),
    "%"
)

# ------------------------------------------------------------
# 7. Create comparison data for graph
# ------------------------------------------------------------

graph_data = pd.DataFrame({
    "Dose": ["MCV1", "MCV2", "DTPCV1", "DTPCV3"],
    "Coverage": [
        mcv["MCV1"].mean(),
        mcv["MCV2"].mean(),
        dtp["DTPCV1"].mean(),
        dtp["DTPCV3"].mean()
    ]
})

# ------------------------------------------------------------
# 8. Bar chart
# ------------------------------------------------------------

plt.figure(figsize=(9, 6))

plt.bar(
    graph_data["Dose"],
    graph_data["Coverage"]
)

plt.title("First Dose vs Subsequent Dose Coverage")
plt.xlabel("Vaccine Dose")
plt.ylabel("Average Coverage (%)")

plt.ylim(0, 100)

plt.tight_layout()
plt.show()

# ============================================================
# VACCINE INTRODUCTION VS DISEASE CASES
# STEP 1: CHECK INTRODUCTION DATA
# ============================================================

import pandas as pd

# ------------------------------------------------------------
# 1. Load Vaccine Introduction data
# ------------------------------------------------------------

intro_df = pd.read_excel(
    "/content/drive/MyDrive/Vaccination_Project/Dataset/cleaned_vaccine-introduction-data.xlsx"
)

print("===== VACCINE INTRODUCTION DATA =====")
print("Shape:", intro_df.shape)

print("\nColumns:")
print(intro_df.columns.tolist())

# ------------------------------------------------------------
# 2. Show first 10 records
# ------------------------------------------------------------

print("\n===== FIRST 10 RECORDS =====")

display(intro_df.head(10))

# ------------------------------------------------------------
# 3. Check missing values
# ------------------------------------------------------------

print("\n===== MISSING VALUES =====")

print(intro_df.isnull().sum())

# ------------------------------------------------------------
# 4. Check Intro column values
# ------------------------------------------------------------

print("\n===== INTRO COLUMN VALUES =====")

print(
    intro_df["Intro"]
    .value_counts(dropna=False)
    .head(20)
)

# ------------------------------------------------------------
# 5. Check vaccine descriptions
# ------------------------------------------------------------

print("\n===== UNIQUE VACCINE DESCRIPTIONS =====")

print(
    intro_df["Description"]
    .dropna()
    .astype(str)
    .drop_duplicates()
    .tolist()
)

# ------------------------------------------------------------
# 6. Load Reported Cases data
# ------------------------------------------------------------

cases_df = pd.read_excel(
    "/content/drive/MyDrive/Vaccination_Project/Dataset/cleaned_reported-cases-data.xlsx"
)

print("\n===== REPORTED CASES DATA =====")

print("Shape:", cases_df.shape)

print("\nColumns:")
print(cases_df.columns.tolist())

# ------------------------------------------------------------
# 7. Disease list
# ------------------------------------------------------------

print("\n===== DISEASES IN REPORTED CASES =====")

print(
    cases_df["DISEASE"]
    .dropna()
    .unique()
)

# ------------------------------------------------------------
# 8. Measles-related vaccine descriptions
# ------------------------------------------------------------

print("\n===== MEASLES-RELATED VACCINE DESCRIPTIONS =====")

measles_intro = intro_df[
    intro_df["Description"]
    .astype(str)
    .str.contains(
        "measles|MCV|MMR",
        case=False,
        na=False
    )
]

display(
    measles_intro[
        [
            "ISO_3_Code",
            "Country Name",
            "WHO Region",
            "Year",
            "Description",
            "Intro"
        ]
    ].head(30)
)

print(
    "\nNumber of measles-related introduction records:",
    len(measles_intro)
)

import os

print("===== EXCEL FILES AVAILABLE IN COLAB =====")

for root, dirs, files in os.walk("/content"):
    for file in files:
        if file.endswith(".xlsx"):
            print(os.path.join(root, file))

import os

print(os.listdir("/content"))

# ============================================================
# VACCINE INTRODUCTION DATA - LOAD AND CHECK
# ============================================================

import pandas as pd

# Load vaccine introduction data
intro_df = pd.read_excel(
    "/content/cleaned_vaccine-introduction-data.xlsx"
)

print("===== VACCINE INTRODUCTION DATA =====")
print("Shape:", intro_df.shape)

print("\n===== COLUMNS =====")
print(intro_df.columns.tolist())

print("\n===== FIRST 10 RECORDS =====")
display(intro_df.head(10))

print("\n===== MISSING VALUES =====")
display(intro_df.isnull().sum())

print("\n===== INTRO VALUES =====")
display(
    intro_df["Intro"]
    .value_counts(dropna=False)
)

print("\n===== VACCINE DESCRIPTIONS =====")
display(
    intro_df["Description"]
    .dropna()
    .astype(str)
    .drop_duplicates()
    .sort_values()
    .to_frame()
)

print("===== INTRO VALUES =====")

display(
    intro_df["INTRO"].value_counts(dropna=False)
)

print("\n===== VACCINE DESCRIPTIONS =====")

display(
    intro_df["DESCRIPTION"]
    .dropna()
    .astype(str)
    .drop_duplicates()
    .sort_values()
    .to_frame()
)

# ============================================================
# VACCINE INTRODUCTION VS MEASLES CASES
# STEP 2: PREPARE INTRODUCTION DATA
# ============================================================

# ------------------------------------------------------------
# 1. Select Measles-containing vaccine
# ------------------------------------------------------------

measles_intro = intro_df[
    intro_df["DESCRIPTION"]
    .astype(str)
    .str.contains(
        "Measles-containing vaccine",
        case=False,
        na=False
    )
].copy()

print("===== MEASLES VACCINE INTRODUCTION =====")
print("Records:", len(measles_intro))

display(
    measles_intro.head(20)
)

# ------------------------------------------------------------
# 2. Create introduction status
# ------------------------------------------------------------

measles_intro["INTRODUCED"] = (
    measles_intro["INTRO"]
    .astype(str)
    .str.startswith("Yes")
)

# ------------------------------------------------------------
# 3. Country-year introduction summary
# ------------------------------------------------------------

intro_summary = (
    measles_intro
    .groupby(["ISO_3_CODE", "COUNTRYNAME", "YEAR"])
    ["INTRODUCED"]
    .max()
    .reset_index()
)

print("\n===== INTRODUCTION SUMMARY =====")

display(
    intro_summary.head(20)
)

# ------------------------------------------------------------
# 4. Load reported cases
# ------------------------------------------------------------

cases_df = pd.read_excel(
    "/content/cleaned_reported-cases-data.xlsx"
)

print("\n===== REPORTED CASES =====")
print("Shape:", cases_df.shape)

# ------------------------------------------------------------
# 5. Filter Measles cases
# ------------------------------------------------------------

measles_cases = cases_df[
    cases_df["DISEASE"] == "MEASLES"
].copy()

print("\n===== MEASLES CASES =====")
print("Records:", len(measles_cases))

display(
    measles_cases.head(10)
)

# ------------------------------------------------------------
# 6. Check columns
# ------------------------------------------------------------

print("\nIntroduction columns:")
print(intro_summary.columns.tolist())

print("\nCases columns:")
print(measles_cases.columns.tolist())

import os

print(os.listdir("/content"))

# ============================================================
# MEASLES VACCINE INTRODUCTION VS REPORTED CASES
# ============================================================

import pandas as pd

# ------------------------------------------------------------
# 1. Load reported cases
# ------------------------------------------------------------

cases_df = pd.read_excel(
    "/content/cleaned_reported-cases-data.xlsx"
)

# ------------------------------------------------------------
# 2. Filter Measles cases
# ------------------------------------------------------------

measles_cases = cases_df[
    cases_df["DISEASE"] == "MEASLES"
].copy()

# Keep required columns
measles_cases = measles_cases[
    ["CODE", "NAME", "YEAR", "CASES"]
].copy()

# ------------------------------------------------------------
# 3. Prepare introduction data
# ------------------------------------------------------------

# We already created measles_intro earlier.
# Keep only required columns.

intro_data = measles_intro[
    ["ISO_3_CODE", "COUNTRYNAME", "YEAR", "INTRODUCED"]
].copy()

# Rename columns to match cases data
intro_data = intro_data.rename(
    columns={
        "ISO_3_CODE": "CODE",
        "COUNTRYNAME": "NAME"
    }
)

# ------------------------------------------------------------
# 4. Merge introduction and cases
# ------------------------------------------------------------

measles_analysis = pd.merge(
    intro_data,
    measles_cases,
    on=["CODE", "NAME", "YEAR"],
    how="inner"
)

# ------------------------------------------------------------
# 5. Display result
# ------------------------------------------------------------

print("===== MEASLES INTRODUCTION VS CASES =====")

print("Records:", len(measles_analysis))

print(
    "Countries/Regions:",
    measles_analysis["CODE"].nunique()
)

print(
    "Year range:",
    measles_analysis["YEAR"].min(),
    "to",
    measles_analysis["YEAR"].max()
)

display(
    measles_analysis.head(20)
)

# ------------------------------------------------------------
# 6. Compare cases by introduction status
# ------------------------------------------------------------

print("\n===== CASES BY INTRODUCTION STATUS =====")

case_summary = (
    measles_analysis
    .groupby("INTRODUCED")["CASES"]
    .agg(
        Records="count",
        Average_Cases="mean",
        Median_Cases="median",
        Total_Cases="sum"
    )
    .reset_index()
)

case_summary["Average_Cases"] = case_summary["Average_Cases"].round(2)
case_summary["Median_Cases"] = case_summary["Median_Cases"].round(2)

display(case_summary)

import matplotlib.pyplot as plt

chart_data = case_summary.copy()

labels = ["Not Introduced", "Introduced"]

values = [
    chart_data.loc[
        chart_data["INTRODUCED"] == False,
        "Average_Cases"
    ].iloc[0],

    chart_data.loc[
        chart_data["INTRODUCED"] == True,
        "Average_Cases"
    ].iloc[0]
]

plt.figure(figsize=(8, 6))

plt.bar(labels, values)

plt.title(
    "Average Measles Cases by Vaccine Introduction Status"
)

plt.xlabel("Measles Vaccine Introduction Status")
plt.ylabel("Average Reported Measles Cases")

plt.tight_layout()
plt.show()

# ============================================================
# BOOSTER UPTAKE OVER TIME
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

# ------------------------------------------------------------
# 1. Select booster-related antigens
# ------------------------------------------------------------

booster_antigens = [
    "TT2PLUS",
    "TTCV4",
    "TTCV5",
    "TTCV6"
]

booster_df = df[
    df["ANTIGEN"].isin(booster_antigens)
].copy()

# ------------------------------------------------------------
# 2. Remove missing coverage
# ------------------------------------------------------------

booster_df = booster_df.dropna(
    subset=["COVERAGE"]
)

# Keep valid percentage values only
booster_df = booster_df[
    (booster_df["COVERAGE"] >= 0) &
    (booster_df["COVERAGE"] <= 100)
]

# ------------------------------------------------------------
# 3. Calculate year-wise average coverage
# ------------------------------------------------------------

booster_trend = (
    booster_df
    .groupby(["YEAR", "ANTIGEN"])["COVERAGE"]
    .mean()
    .reset_index()
)

# ------------------------------------------------------------
# 4. Round values
# ------------------------------------------------------------

booster_trend["COVERAGE"] = booster_trend["COVERAGE"].round(2)

print("===== BOOSTER UPTAKE OVER TIME =====")

display(
    booster_trend.head(20)
)

# ------------------------------------------------------------
# 5. Pivot for easier viewing
# ------------------------------------------------------------

booster_pivot = booster_trend.pivot(
    index="YEAR",
    columns="ANTIGEN",
    values="COVERAGE"
).reset_index()

print("\n===== YEAR-WISE BOOSTER COVERAGE =====")

display(
    booster_pivot.head(20)
)

# ------------------------------------------------------------
# 6. Overall statistics
# ------------------------------------------------------------

print("\n===== BOOSTER SUMMARY =====")

for antigen in booster_antigens:

    temp = booster_trend[
        booster_trend["ANTIGEN"] == antigen
    ]

    if len(temp) > 0:

        print(
            antigen,
            "Average Coverage:",
            round(temp["COVERAGE"].mean(), 2),
            "%"
        )

        print(
            "Highest Year:",
            int(
                temp.loc[
                    temp["COVERAGE"].idxmax(),
                    "YEAR"
                ]
            ),
            "| Coverage:",
            round(
                temp["COVERAGE"].max(),
                2
            ),
            "%"
        )

        print(
            "Lowest Year:",
            int(
                temp.loc[
                    temp["COVERAGE"].idxmin(),
                    "YEAR"
                ]
            ),
            "| Coverage:",
            round(
                temp["COVERAGE"].min(),
                2
            ),
            "%"
        )

        print()

# ------------------------------------------------------------
# 7. Line graph
# ------------------------------------------------------------

plt.figure(figsize=(12, 6))

for antigen in booster_antigens:

    temp = booster

# ============================================================
# BOOSTER UPTAKE OVER TIME - LINE GRAPH
# ============================================================

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))

# TT2PLUS
temp = booster_trend[
    booster_trend["ANTIGEN"] == "TT2PLUS"
]

plt.plot(
    temp["YEAR"],
    temp["COVERAGE"],
    marker="o",
    label="TT2PLUS"
)

# TTCV4
temp = booster_trend[
    booster_trend["ANTIGEN"] == "TTCV4"
]

plt.plot(
    temp["YEAR"],
    temp["COVERAGE"],
    marker="o",
    label="TTCV4"
)

# TTCV5
temp = booster_trend[
    booster_trend["ANTIGEN"] == "TTCV5"
]

plt.plot(
    temp["YEAR"],
    temp["COVERAGE"],
    marker="o",
    label="TTCV5"
)

# TTCV6
temp = booster_trend[
    booster_trend["ANTIGEN"] == "TTCV6"
]

plt.plot(
    temp["YEAR"],
    temp["COVERAGE"],
    marker="o",
    label="TTCV6"
)

# Graph settings
plt.title("Booster Vaccination Coverage Over Time")

plt.xlabel("Year")

plt.ylabel("Average Coverage (%)")

plt.ylim(0, 100)

plt.legend()

plt.grid(True)

plt.tight_layout()

plt.show()

# ============================================================
# HIGH VACCINATION COVERAGE BUT HIGH MEASLES INCIDENCE
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

# ------------------------------------------------------------
# 1. Check the available columns
# ------------------------------------------------------------

print("Columns available:")
print(measles_analysis.columns.tolist())


# ------------------------------------------------------------
# 2. Keep only valid vaccination coverage and incidence
# ------------------------------------------------------------

high_vaccination_data = measles_analysis[
    (measles_analysis["COVERAGE"] >= 90) &
    (measles_analysis["INCIDENCE_RATE"].notna()) &
    (measles_analysis["INCIDENCE_RATE"] > 0)
].copy()


# ------------------------------------------------------------
# 3. Find the 75th percentile of measles incidence
# ------------------------------------------------------------

incidence_75th = high_vaccination_data[
    "INCIDENCE_RATE"
].quantile(0.75)

print(
    "\n75th Percentile of Incidence:",
    round(incidence_75th, 2)
)


# ------------------------------------------------------------
# 4. Select high vaccination + high incidence records
# ------------------------------------------------------------

high_vacc_high_incidence = high_vaccination_data[
    high_vaccination_data["INCIDENCE_RATE"] >= incidence_75th
].copy()


# ------------------------------------------------------------
# 5. Sort by incidence
# ------------------------------------------------------------

high_vacc_high_incidence = (
    high_vacc_high_incidence
    .sort_values(
        by="INCIDENCE_RATE",
        ascending=False
    )
)


# ------------------------------------------------------------
# 6. Display top records
# ------------------------------------------------------------

print("\n===== HIGH VACCINATION + HIGH INCIDENCE =====")

display(
    high_vacc_high_incidence[
        [
            "CODE",
            "NAME",
            "YEAR",
            "COVERAGE",
            "INCIDENCE_RATE"
        ]
    ].head(20)
)


# ------------------------------------------------------------
# 7. Summary
# ------------------------------------------------------------

print("\n===== SUMMARY =====")

print(
    "Total high vaccination + high incidence records:",
    len(high_vacc_high_incidence)
)

print(
    "Countries/Regions:",
    high_vacc_high_incidence["CODE"].nunique()
)

print(
    "Average vaccination coverage:",
    round(
        high_vacc_high_incidence["COVERAGE"].mean(),
        2
    ),
    "%"
)

print(
    "Average measles incidence:",
    round(
        high_vacc_high_incidence["INCIDENCE_RATE"].mean(),
        2
    )
)

print(
    "Highest measles incidence:",
    round(
        high_vacc_high_incidence["INCIDENCE_RATE"].max(),
        2
    )
)


# ------------------------------------------------------------
# 8. Scatter plot
# ------------------------------------------------------------

plt.figure(figsize=(10, 6))

plt.scatter(
    measles_analysis["COVERAGE"],
    measles_analysis["INCIDENCE_RATE"],
    alpha=0.3
)

plt.axvline(
    90,
    linestyle="--",
    label="90% Vaccination Coverage"
)

plt.xlabel("Measles Vaccination Coverage (%)")

plt.ylabel("Measles Incidence Rate")

plt.title(
    "High Vaccination Coverage vs Measles Incidence"
)

plt.legend()

plt.grid(True)

plt.tight_layout()

plt.show()

# ============================================================
# HIGH VACCINATION COVERAGE + HIGH MEASLES INCIDENCE
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

# ------------------------------------------------------------
# 1. Select measles vaccination antigens
# ------------------------------------------------------------

measles_antigens = ["MCV1", "MCV2", "MCV2X2"]

measles_coverage = df[
    df["ANTIGEN"].isin(measles_antigens)
].copy()


# ------------------------------------------------------------
# 2. Keep valid vaccination coverage values
# ------------------------------------------------------------

measles_coverage = measles_coverage.dropna(
    subset=["COVERAGE"]
)

measles_coverage = measles_coverage[
    (measles_coverage["COVERAGE"] >= 0) &
    (measles_coverage["COVERAGE"] <= 100)
]


# ------------------------------------------------------------
# 3. Calculate average measles vaccination coverage
#    for each country and year
# ------------------------------------------------------------

measles_coverage_yearly = (
    measles_coverage
    .groupby(["CODE", "NAME", "YEAR"])["COVERAGE"]
    .mean()
    .reset_index()
)


# ------------------------------------------------------------
# 4. Get measles incidence data
# ------------------------------------------------------------

measles_incidence = incidence_clean[
    incidence_clean["DISEASE"] == "MEASLES"
].copy()

measles_incidence = measles_incidence[
    ["

# ============================================================
# HIGH VACCINATION COVERAGE + HIGH MEASLES INCIDENCE
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

# 1. Measles vaccine antigens
measles_antigens = ["MCV1", "MCV2", "MCV2X2"]

measles_coverage = df[
    df["ANTIGEN"].isin(measles_antigens)
].copy()

# 2. Keep valid coverage values
measles_coverage = measles_coverage.dropna(
    subset=["COVERAGE"]
)

measles_coverage = measles_coverage[
    (measles_coverage["COVERAGE"] >= 0) &
    (measles_coverage["COVERAGE"] <= 100)
]

# 3. Country-year average vaccination coverage
measles_coverage_yearly = (
    measles_coverage
    .groupby(["CODE", "NAME", "YEAR"])["COVERAGE"]
    .mean()
    .reset_index()
)

# 4. Select measles incidence
measles_incidence = incidence_clean[
    incidence_clean["DISEASE"] == "MEASLES"
].copy()

measles_incidence = measles_incidence[
    ["CODE", "NAME", "YEAR", "INCIDENCE_RATE"]
]

# 5. Merge coverage + incidence
coverage_incidence = pd.merge(
    measles_coverage_yearly,
    measles_incidence,
    on=["CODE", "NAME", "YEAR"],
    how="inner"
)

# 6. Remove missing incidence
coverage_incidence = coverage_incidence.dropna(
    subset=["INCIDENCE_RATE"]
)

# Keep non-negative incidence
coverage_incidence = coverage_incidence[
    coverage_incidence["INCIDENCE_RATE"] >= 0
]

# 7. High vaccination coverage = 90% or more
high_vaccination = coverage_incidence[
    coverage_incidence["COVERAGE"] >= 90
].

# HIGH VACCINATION + HIGH MEASLES INCIDENCE

# Measles vaccine coverage
m = df[df["ANTIGEN"].isin(["MCV1", "MCV2", "MCV2X2"])].copy()

# Valid coverage only
m = m.dropna(subset=["COVERAGE"])
m = m[(m["COVERAGE"] >= 0) & (m["COVERAGE"] <= 100)]

# Country-year average coverage
m = m.groupby(
    ["CODE", "NAME", "YEAR"],
    as_index=False
)["COVERAGE"].mean()

# Measles incidence
c = incidence_clean[
    incidence_clean["DISEASE"] == "MEASLES"
].copy()

c = c[
    ["CODE", "NAME", "YEAR", "INCIDENCE_RATE"]
]

# Merge
result = pd.merge(
    m,
    c,
    on=["CODE", "NAME", "YEAR"],
    how="inner"
)

# High vaccination coverage
result = result[result["COVERAGE"] >= 90].copy()

# Remove missing incidence
result = result.dropna(
    subset=["INCIDENCE_RATE"]
)

# High incidence threshold
threshold = result["INCIDENCE_RATE"].quantile(0.75)

# High vaccination + high incidence
high = result[
    result["INCIDENCE_RATE"] >= threshold
].copy()

# Sort
high = high.sort_values(
    "INCIDENCE_RATE",
    ascending=False
)

print("High vaccination coverage: 90% or more")
print("High incidence threshold:", round(threshold, 2))
print("Total records:", len(high))

print("\nTOP 20 RECORDS:")

print(
    high[
        ["CODE", "NAME", "YEAR", "COVERAGE", "INCIDENCE_RATE"]
    ].head(20).to_string(index=False)
)

print("\nAverage vaccination coverage:",
      round(high["COVERAGE"].mean(), 2), "%")

print("Average measles incidence:",
      round(high["INCIDENCE_RATE"].mean(), 2))

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))

plt.scatter(
    result["COVERAGE"],
    result["INCIDENCE_RATE"],
    alpha=0.3
)

plt.axvline(
    90,
    linestyle="--",
    label="90% Coverage"
)

plt.xlabel("Measles Vaccination Coverage (%)")
plt.ylabel("Measles Incidence Rate")
plt.title("Measles Vaccination Coverage vs Incidence")

plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# ============================================================
# GEOGRAPHIC DISEASE PREVALENCE - MEASLES
# ============================================================

import pandas as pd
import matplotlib.pyplot as plt

# 1. Select measles records
geo_measles = incidence_clean[
    incidence_clean["DISEASE"] == "MEASLES"
].copy()

# 2. Remove missing incidence values
geo_measles = geo_measles.dropna(
    subset=["INCIDENCE_RATE"]
)

# 3. Calculate average incidence by country/region
country_incidence = (
    geo_measles
    .groupby(["CODE", "NAME"])["INCIDENCE_RATE"]
    .agg(
        Average_Incidence="mean",
        Total_Records="count"
    )
    .reset_index()
)

# 4. Sort from highest to lowest
country_incidence = country_incidence.sort_values(
    "Average_Incidence",
    ascending=False
)

# 5. Display top 15 countries/regions
print("===== TOP 15 COUNTRIES/REGIONS BY AVERAGE MEASLES INCIDENCE =====")

display(
    country_incidence.head(15)
)

# 6. Summary
print("\n===== SUMMARY =====")

print(
    "Total countries/regions:",
    country_incidence["CODE"].nunique()
)

print(
    "Highest average incidence:",
    round(
        country_incidence["Average_Incidence"].max(),
        2
    )
)

top_country = country_incidence.iloc[0]

print(
    "Country/Region with highest average incidence:",
    top_country["NAME"]
)

print(
    "Average incidence:",
    round(
        top_country["Average_Incidence"],
        2
    )
)

# 7. Bar chart - Top 15
top15 = country_incidence.head(15).sort_values(
    "Average_Incidence"
)

plt.figure(figsize=(10, 7))

plt.barh(
    top15["NAME"],
    top15["Average_Incidence"]
)

plt.xlabel("Average Measles Incidence Rate")

plt.ylabel("Country / Region")

plt.title(
    "Top 15 Countries/Regions by Average Measles Incidence"
)

plt.tight_layout()

plt.show()